// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ti2026.Data;

#nullable disable

namespace Ti2026.Data.Migrations
{
    [DbContext(typeof(Ti2026DbContext))]
    [Migration("20260811095145_AddIdolTeamFarmRank")]
    partial class AddIdolTeamFarmRank
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Ti2026.Data.Entities.DraftEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPick")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRadiant")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.HasIndex("MatchId", "Order")
                        .IsUnique();

                    b.ToTable("DraftEvents");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Hero", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageMediaAssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalizedName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.HeroStat", b =>
                {
                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("HighPick")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HighWin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProBan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProPick")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProWin")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PubPick")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PubWin")
                        .HasColumnType("INTEGER");

                    b.HasKey("HeroId");

                    b.ToTable("HeroStats");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.IdolMatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CampsStacked")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DamageTaken")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Denies")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DetailFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FirstKillSecond")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameMode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GoldAdv10")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GoldAdv20")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GoldAdv30")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GoldPerMin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeroDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeroHealing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdolPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRadiant")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsRoaming")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Lane")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LaneEfficiency")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LaneRole")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastHits")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LobbyType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NetWorth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ObsPlaced")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SenPlaced")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Stuns")
                        .HasColumnType("REAL");

                    b.Property<long?>("TeamDamageTaken")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamDeaths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamFarmRank")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TeamHeroDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamKills")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TeamNetWorth")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TeamfightParticipation")
                        .HasColumnType("REAL");

                    b.Property<int?>("TowerDamage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Won")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("XpPerMin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartTime");

                    b.HasIndex("IdolPlayerId", "MatchId")
                        .IsUnique();

                    b.ToTable("IdolMatches");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.IdolPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeclaredRole")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MatchesFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonaName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProfileFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("NameKey")
                        .IsUnique();

                    b.ToTable("IdolPlayers");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.IngestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemsWritten")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Source", "StartedAt");

                    b.ToTable("IngestRuns");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Item", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quality")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.ItemPurchase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRadiant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerSlot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("HeroId", "ItemKey");

                    b.ToTable("ItemPurchases");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.League", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Tier");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Match", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComebackGold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DetailSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DetailsIngestedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DireScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DireTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FirstBloodTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FirstRoshanSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeagueName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatchVersion")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("RadiantHadFirstBlood")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("RadiantReachedTenFirst")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RadiantScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RadiantTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RadiantWin")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ThrowGold")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DetailsIngestedAt");

                    b.HasIndex("SeriesId");

                    b.HasIndex("StartTime");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.MatchPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Buybacks")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CampsStacked")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CourierKills")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeathsToTormentor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Denies")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("FirstBloodClaimed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldPerMin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeroDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRadiant")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KillsFirst10Min")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Lane")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LaneEfficiencyPct")
                        .HasColumnType("REAL");

                    b.Property<int?>("LaneRole")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastHits")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LotusItems")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Lotuses")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MadstoneBundles")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NetWorth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ObserverKills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ObserversPlaced")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoshanKills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RunePickups")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SentriesPlaced")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SentryKills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Smokes")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("StunSeconds")
                        .HasColumnType("REAL");

                    b.Property<double?>("TeamfightParticipation")
                        .HasColumnType("REAL");

                    b.Property<int?>("TormentorKills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TowerDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TowerKills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Watchers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpPerMin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MatchId", "AccountId")
                        .IsUnique();

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ETag")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("SourceUrl")
                        .IsUnique();

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NickKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("OpenDotaAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PhotoMediaAssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("RealName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NickKey")
                        .IsUnique();

                    b.HasIndex("OpenDotaAccountId")
                        .IsUnique()
                        .HasFilter("\"OpenDotaAccountId\" IS NOT NULL");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("EloA")
                        .HasColumnType("REAL");

                    b.Property<double>("EloB")
                        .HasColumnType("REAL");

                    b.Property<double>("ProbabilityA")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ResolvedMatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamAId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("TeamAWon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamBId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ResolvedMatchId");

                    b.HasIndex("TeamAId");

                    b.HasIndex("TeamBId");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.ProPubMatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LobbyType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Won")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.HasIndex("StartTime");

                    b.HasIndex("PlayerId", "MatchId")
                        .IsUnique();

                    b.ToTable("ProPubMatches");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.RosterEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId", "PlayerId")
                        .IsUnique()
                        .HasFilter("\"ValidTo\" IS NULL");

                    b.HasIndex("TeamId", "ValidTo");

                    b.ToTable("RosterEntries");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.ScheduledSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasStarted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IncomingNodeId1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IncomingNodeId2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LosingNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamId1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamId2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ValveTeamId1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ValveTeamId2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinningNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wins1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wins2")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId1");

                    b.HasIndex("TeamId2");

                    b.HasIndex("LeagueId", "NodeId")
                        .IsUnique();

                    b.ToTable("ScheduledSeries");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.SeedState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SeedStates");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.StyleAnchor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllAssists")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AllDamageTaken")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllDeaths")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AllHeroDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllKills")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AllLaneEfficiency")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AllLastHits")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AllNetWorth")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AllTowerDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LaneEfficiencyCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pool")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Pool", "MatchId")
                        .IsUnique();

                    b.ToTable("StyleAnchors");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LogoMediaAssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OpenDotaTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Qualification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OpenDotaTeamId")
                        .IsUnique()
                        .HasFilter("\"OpenDotaTeamId\" IS NOT NULL");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TeamAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("Alias", "Source")
                        .IsUnique();

                    b.ToTable("TeamAliases");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TeamOpenDotaId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OpenDotaTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OpenDotaTeamId")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("TeamOpenDotaIds");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TeamStatSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AvgAssists")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgDeaths")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgDurationMinutes")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgKills")
                        .HasColumnType("REAL");

                    b.Property<DateOnly>("CapturedOn")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Elo")
                        .HasColumnType("REAL");

                    b.Property<int?>("EloGames")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("F10Rate")
                        .HasColumnType("REAL");

                    b.Property<double?>("FirstBloodRate")
                        .HasColumnType("REAL");

                    b.Property<double>("KillDiff")
                        .HasColumnType("REAL");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Maps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalKills")
                        .HasColumnType("REAL");

                    b.Property<double?>("WinWhenF10Rate")
                        .HasColumnType("REAL");

                    b.Property<double?>("WinWhenFbRate")
                        .HasColumnType("REAL");

                    b.Property<int>("WindowDays")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Winrate")
                        .HasColumnType("REAL");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "CapturedOn", "WindowDays")
                        .IsUnique();

                    b.ToTable("TeamStatSnapshots");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TierEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.HasIndex("Patch", "HeroId", "Position")
                        .IsUnique();

                    b.ToTable("TierEntries");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TrackedMatchTeammate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonaName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RankTier")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SameParty")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TrackedPlayerMatchId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TrackedPlayerMatchId", "AccountId")
                        .IsUnique();

                    b.ToTable("TrackedMatchTeammates");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TrackedPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonaName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RankTier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SyncNote")
                        .HasColumnType("TEXT");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("TrackedPlayers");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TrackedPlayerHero", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgainstGames")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgainstWins")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Games")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackedPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WithGames")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WithWins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrackedPlayerId", "HeroId")
                        .IsUnique();

                    b.ToTable("TrackedPlayerHeroes");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TrackedPlayerMatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AverageRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Denies")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DetailFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EnemyNetWorth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FightSwingDied")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FightSwingSurvived")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FightsDied")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FightsDiedAhead")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FightsSurvived")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameMode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GoldAdv10")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GoldAdv20")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GoldAdv30")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GoldPerMin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeroDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeroHealing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRadiant")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LaneEfficiency")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LaneRole")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastHits")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LobbyType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatesPctGpm")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatesPctXpm")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NetWorth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ParseRequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartySize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PctAssists")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PctDeaths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PctDenies")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PctGpm")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PctHeroDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PctHeroHealing")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PctKills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PctLastHits")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PctTowerDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PctXpm")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamFarmRank")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamNetWorth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamXpmRank")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TowerDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackedPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TradeFoeDeaths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TradeFoeGold")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TradeMyGold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Won")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("XpPerMin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.HasIndex("StartTime");

                    b.HasIndex("TrackedPlayerId", "MatchId")
                        .IsUnique();

                    b.ToTable("TrackedPlayerMatches");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.DraftEvent", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.IdolMatch", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.IdolPlayer", "IdolPlayer")
                        .WithMany("Matches")
                        .HasForeignKey("IdolPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdolPlayer");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.ItemPurchase", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.MatchPlayer", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Match", "Match")
                        .WithMany("Players")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ti2026.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Prediction", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Team", "TeamA")
                        .WithMany()
                        .HasForeignKey("TeamAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ti2026.Data.Entities.Team", "TeamB")
                        .WithMany()
                        .HasForeignKey("TeamBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TeamA");

                    b.Navigation("TeamB");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.ProPubMatch", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.RosterEntry", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ti2026.Data.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.ScheduledSeries", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Team", "Team1")
                        .WithMany()
                        .HasForeignKey("TeamId1");

                    b.HasOne("Ti2026.Data.Entities.Team", "Team2")
                        .WithMany()
                        .HasForeignKey("TeamId2");

                    b.Navigation("Team1");

                    b.Navigation("Team2");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TeamAlias", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Team", "Team")
                        .WithMany("Aliases")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TeamOpenDotaId", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Team", "Team")
                        .WithMany("OpenDotaIds")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TeamStatSnapshot", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TierEntry", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Hero", "Hero")
                        .WithMany()
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TrackedMatchTeammate", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.TrackedPlayerMatch", "Match")
                        .WithMany("Teammates")
                        .HasForeignKey("TrackedPlayerMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TrackedPlayerHero", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.TrackedPlayer", "TrackedPlayer")
                        .WithMany()
                        .HasForeignKey("TrackedPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedPlayer");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TrackedPlayerMatch", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.TrackedPlayer", "TrackedPlayer")
                        .WithMany()
                        .HasForeignKey("TrackedPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedPlayer");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.IdolPlayer", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Match", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Team", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("OpenDotaIds");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TrackedPlayerMatch", b =>
                {
                    b.Navigation("Teammates");
                });
#pragma warning restore 612, 618
        }
    }
}
