// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ti2026.Data;

#nullable disable

namespace Ti2026.Data.Migrations
{
    [DbContext(typeof(Ti2026DbContext))]
    [Migration("20260805075203_AddProPubMatches")]
    partial class AddProPubMatches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Ti2026.Data.Entities.DraftEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPick")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRadiant")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.HasIndex("MatchId", "Order")
                        .IsUnique();

                    b.ToTable("DraftEvents");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Hero", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageMediaAssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalizedName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.HeroStat", b =>
                {
                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("HighPick")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HighWin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProBan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProPick")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProWin")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PubPick")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PubWin")
                        .HasColumnType("INTEGER");

                    b.HasKey("HeroId");

                    b.ToTable("HeroStats");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.IngestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemsWritten")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Source", "StartedAt");

                    b.ToTable("IngestRuns");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Item", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quality")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.ItemPurchase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRadiant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerSlot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("HeroId", "ItemKey");

                    b.ToTable("ItemPurchases");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.League", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Tier");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Match", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComebackGold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DetailSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DetailsIngestedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DireScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DireTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FirstBloodTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FirstRoshanSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeagueName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatchVersion")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("RadiantHadFirstBlood")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("RadiantReachedTenFirst")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RadiantScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RadiantTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RadiantWin")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ThrowGold")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DetailsIngestedAt");

                    b.HasIndex("SeriesId");

                    b.HasIndex("StartTime");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.MatchPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Buybacks")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CampsStacked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Denies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldPerMin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeroDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRadiant")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KillsFirst10Min")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Lane")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LaneEfficiencyPct")
                        .HasColumnType("REAL");

                    b.Property<int?>("LaneRole")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastHits")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NetWorth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ObserversPlaced")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RunePickups")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SentriesPlaced")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("StunSeconds")
                        .HasColumnType("REAL");

                    b.Property<double?>("TeamfightParticipation")
                        .HasColumnType("REAL");

                    b.Property<int?>("TowerDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpPerMin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MatchId", "AccountId")
                        .IsUnique();

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ETag")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("SourceUrl")
                        .IsUnique();

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NickKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("OpenDotaAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PhotoMediaAssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("RealName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NickKey")
                        .IsUnique();

                    b.HasIndex("OpenDotaAccountId")
                        .IsUnique()
                        .HasFilter("\"OpenDotaAccountId\" IS NOT NULL");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("EloA")
                        .HasColumnType("REAL");

                    b.Property<double>("EloB")
                        .HasColumnType("REAL");

                    b.Property<double>("ProbabilityA")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ResolvedMatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamAId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("TeamAWon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamBId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ResolvedMatchId");

                    b.HasIndex("TeamAId");

                    b.HasIndex("TeamBId");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.ProPubMatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LobbyType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Won")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.HasIndex("StartTime");

                    b.HasIndex("PlayerId", "MatchId")
                        .IsUnique();

                    b.ToTable("ProPubMatches");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.RosterEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId", "PlayerId")
                        .IsUnique()
                        .HasFilter("\"ValidTo\" IS NULL");

                    b.HasIndex("TeamId", "ValidTo");

                    b.ToTable("RosterEntries");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.SeedState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SeedStates");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LogoMediaAssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OpenDotaTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Qualification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OpenDotaTeamId")
                        .IsUnique()
                        .HasFilter("\"OpenDotaTeamId\" IS NOT NULL");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TeamAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("Alias", "Source")
                        .IsUnique();

                    b.ToTable("TeamAliases");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TeamStatSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AvgAssists")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgDeaths")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgDurationMinutes")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgKills")
                        .HasColumnType("REAL");

                    b.Property<DateOnly>("CapturedOn")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Elo")
                        .HasColumnType("REAL");

                    b.Property<double?>("F10Rate")
                        .HasColumnType("REAL");

                    b.Property<double?>("FirstBloodRate")
                        .HasColumnType("REAL");

                    b.Property<double>("KillDiff")
                        .HasColumnType("REAL");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Maps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalKills")
                        .HasColumnType("REAL");

                    b.Property<double?>("WinWhenF10Rate")
                        .HasColumnType("REAL");

                    b.Property<double?>("WinWhenFbRate")
                        .HasColumnType("REAL");

                    b.Property<int>("WindowDays")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Winrate")
                        .HasColumnType("REAL");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "CapturedOn", "WindowDays")
                        .IsUnique();

                    b.ToTable("TeamStatSnapshots");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TierEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.HasIndex("Patch", "HeroId", "Position")
                        .IsUnique();

                    b.ToTable("TierEntries");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.DraftEvent", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.ItemPurchase", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.MatchPlayer", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Match", "Match")
                        .WithMany("Players")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ti2026.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Prediction", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Team", "TeamA")
                        .WithMany()
                        .HasForeignKey("TeamAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ti2026.Data.Entities.Team", "TeamB")
                        .WithMany()
                        .HasForeignKey("TeamBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TeamA");

                    b.Navigation("TeamB");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.ProPubMatch", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.RosterEntry", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ti2026.Data.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TeamAlias", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Team", "Team")
                        .WithMany("Aliases")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TeamStatSnapshot", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TierEntry", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Hero", "Hero")
                        .WithMany()
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Match", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Team", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
