// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ti2026.Data;

#nullable disable

namespace Ti2026.Data.Migrations
{
    [DbContext(typeof(Ti2026DbContext))]
    partial class Ti2026DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Ti2026.Data.Entities.Hero", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageMediaAssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalizedName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.IngestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemsWritten")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Source", "StartedAt");

                    b.ToTable("IngestRuns");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Match", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DireScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DireTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FirstBloodTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeagueName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatchVersion")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("RadiantHadFirstBlood")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("RadiantReachedTenFirst")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RadiantScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RadiantTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RadiantWin")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.HasIndex("StartTime");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ETag")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("SourceUrl")
                        .IsUnique();

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NickKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("OpenDotaAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PhotoMediaAssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("RealName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NickKey")
                        .IsUnique();

                    b.HasIndex("OpenDotaAccountId")
                        .IsUnique()
                        .HasFilter("\"OpenDotaAccountId\" IS NOT NULL");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.RosterEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId", "PlayerId")
                        .IsUnique()
                        .HasFilter("\"ValidTo\" IS NULL");

                    b.HasIndex("TeamId", "ValidTo");

                    b.ToTable("RosterEntries");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.SeedState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SeedStates");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LogoMediaAssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Qualification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TeamAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("Alias", "Source")
                        .IsUnique();

                    b.ToTable("TeamAliases");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TeamStatSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvgAssists")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgDeaths")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgDurationMinutes")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgKills")
                        .HasColumnType("REAL");

                    b.Property<DateOnly>("CapturedOn")
                        .HasColumnType("TEXT");

                    b.Property<double>("F10Rate")
                        .HasColumnType("REAL");

                    b.Property<double>("FirstBloodRate")
                        .HasColumnType("REAL");

                    b.Property<double>("KillDiff")
                        .HasColumnType("REAL");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Maps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalKills")
                        .HasColumnType("REAL");

                    b.Property<double>("WinWhenF10Rate")
                        .HasColumnType("REAL");

                    b.Property<double>("WinWhenFbRate")
                        .HasColumnType("REAL");

                    b.Property<int>("WindowDays")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Winrate")
                        .HasColumnType("REAL");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "CapturedOn", "WindowDays")
                        .IsUnique();

                    b.ToTable("TeamStatSnapshots");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TierEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.HasIndex("Patch", "HeroId", "Position")
                        .IsUnique();

                    b.ToTable("TierEntries");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.RosterEntry", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ti2026.Data.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TeamAlias", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Team", "Team")
                        .WithMany("Aliases")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TeamStatSnapshot", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.TierEntry", b =>
                {
                    b.HasOne("Ti2026.Data.Entities.Hero", "Hero")
                        .WithMany()
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("Ti2026.Data.Entities.Team", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
